POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Efrén",
  "lastName": "Ruíz Rubio",
  "email": "efren282@outlook.es",
  "password": "MetroEFTW1!",
  "role": "admin"
}