POST http://localhost:3001/api/enterprises
Content-Type: application/json

{
  "name": "Empresa 5",
  "turn": "Giro 5",
  "address": "Dirección 5",
  "telephone": "Teléfono 5",
  "amountOfEmployees": "fa",
  "admins": ["1"]
}